/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../../../utils/Gtil/inc/GtilVersions.h"


#ifndef ATILIMAGEAPIMAJORVERSION
#define ATILIMAGEAPIMAJORVERSION GTILIMAGEAPIMAJORVERSION
#endif

#ifndef ATILIMAGEAPIMIMORVERSION
#define ATILIMAGEAPIMIMORVERSION GTILIMAGEAPIMIMORVERSION
#endif

#ifndef ATILSUBSYSTEMAPIMAJORVERSION
#define ATILSUBSYSTEMAPIMAJORVERSION GTILSUBSYSTEMAPIMAJORVERSION
#endif

#ifndef ATILSUBSYSTEMAPIMINORVERSION
#define ATILSUBSYSTEMAPIMINORVERSION GTILSUBSYSTEMAPIMINORVERSION
#endif

#ifndef ATILFORMATCODECAPIMAJORVERSION
#define ATILFORMATCODECAPIMAJORVERSION GTILFORMATCODECAPIMAJORVERSION
#endif

#ifndef ATILFORMATCODECAPIMINORVERSION
#define ATILFORMATCODECAPIMINORVERSION GTILFORMATCODECAPIMINORVERSION
#endif
