/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../inc/GcStatusBar.h"
#include "acdocman.h"
#include "adesk.h"
#ifndef AcStatusBarItem
#define AcStatusBarItem GcStatusBarItem
#endif

#ifndef ACSB_NOBORDERS
#define ACSB_NOBORDERS GCSB_NOBORDERS
#endif

#ifndef ACSB_INACTIVE
#define ACSB_INACTIVE GCSB_INACTIVE
#endif

#ifndef ACSB_STRETCH
#define ACSB_STRETCH GCSB_STRETCH
#endif

#ifndef ACSB_ACTIVE
#define ACSB_ACTIVE GCSB_ACTIVE
#endif

#ifndef ACSB_COMMAND
#define ACSB_COMMAND GCSB_COMMAND
#endif

#ifndef ACSB_POPUP
#define ACSB_POPUP GCSB_POPUP
#endif

#ifndef ACSB_DIVIDER
#define ACSB_DIVIDER GCSB_DIVIDER
#endif

#ifndef ACSB_SUBDIVIDER
#define ACSB_SUBDIVIDER GCSB_SUBDIVIDER
#endif

#ifndef ACSB_INDETERMINATE
#define ACSB_INDETERMINATE GCSB_INDETERMINATE
#endif

#ifndef ACSB_ONETIME
#define ACSB_ONETIME GCSB_ONETIME
#endif

#ifndef ACSB_POPOUT
#define ACSB_POPOUT GCSB_POPOUT
#endif

#ifndef ACSB_NORMAL
#define ACSB_NORMAL GCSB_NORMAL
#endif

#ifndef AcPane
#define AcPane GcPane
#endif

#ifndef AcTrayItemAnimationCallbackFunc
#define AcTrayItemAnimationCallbackFunc GcTrayItemAnimationCallbackFunc
#endif

#ifndef AcTrayItemAnimationCallbackData
#define AcTrayItemAnimationCallbackData GcTrayItemAnimationCallbackData
#endif

#ifndef AcTrayItemAnimationControl
#define AcTrayItemAnimationControl GcTrayItemAnimationControl
#endif

#ifndef AcTrayItemBubbleWindowCallbackFunc
#define AcTrayItemBubbleWindowCallbackFunc GcTrayItemBubbleWindowCallbackFunc
#endif

#ifndef AcTrayItemBubbleWindowCallbackData
#define AcTrayItemBubbleWindowCallbackData GcTrayItemBubbleWindowCallbackData
#endif

#ifndef AcTrayItemBubbleWindowControl
#define AcTrayItemBubbleWindowControl GcTrayItemBubbleWindowControl
#endif

#ifndef AcRxValue
#define AcRxValue GcRxValue
#endif

#ifndef AcTrayItem
#define AcTrayItem GcTrayItem
#endif

#ifndef AcDefaultPane
#define AcDefaultPane GcDefaultPane
#endif

#ifndef ACSBPANE_APP_MODEMACRO
#define ACSBPANE_APP_MODEMACRO GCSBPANE_APP_MODEMACRO
#endif

#ifndef ACSBPANE_APP_CURSORCOORD
#define ACSBPANE_APP_CURSORCOORD GCSBPANE_APP_CURSORCOORD
#endif

#ifndef ACSBPANE_APP_SNAP
#define ACSBPANE_APP_SNAP GCSBPANE_APP_SNAP
#endif

#ifndef ACSBPANE_APP_GRID
#define ACSBPANE_APP_GRID GCSBPANE_APP_GRID
#endif

#ifndef ACSBPANE_APP_ORTHO
#define ACSBPANE_APP_ORTHO GCSBPANE_APP_ORTHO
#endif

#ifndef ACSBPANE_APP_POLAR
#define ACSBPANE_APP_POLAR GCSBPANE_APP_POLAR
#endif

#ifndef ACSBPANE_APP_OTRACK
#define ACSBPANE_APP_OTRACK GCSBPANE_APP_OTRACK
#endif

#ifndef ACSBPANE_APP_LINEWEIGHT
#define ACSBPANE_APP_LINEWEIGHT GCSBPANE_APP_LINEWEIGHT
#endif

#ifndef ACSBPANE_APP_PAPERMODEL
#define ACSBPANE_APP_PAPERMODEL GCSBPANE_APP_PAPERMODEL
#endif

#ifndef ACSBPANE_APP_PAPER
#define ACSBPANE_APP_PAPER GCSBPANE_APP_PAPER
#endif

#ifndef ACSBPANE_APP_MODEL
#define ACSBPANE_APP_MODEL GCSBPANE_APP_MODEL
#endif

#ifndef ACSBPANE_APP_OSNAP
#define ACSBPANE_APP_OSNAP GCSBPANE_APP_OSNAP
#endif

#ifndef ACSBPANE_APP_FLOAT
#define ACSBPANE_APP_FLOAT GCSBPANE_APP_FLOAT
#endif

#ifndef ACSBPANE_APP_TABLET
#define ACSBPANE_APP_TABLET GCSBPANE_APP_TABLET
#endif

#ifndef ACSBPANE_APP_SPACER
#define ACSBPANE_APP_SPACER GCSBPANE_APP_SPACER
#endif

#ifndef ACSBPANE_APP_VPMAX_PREV
#define ACSBPANE_APP_VPMAX_PREV GCSBPANE_APP_VPMAX_PREV
#endif

#ifndef ACSBPANE_APP_VPMAX
#define ACSBPANE_APP_VPMAX GCSBPANE_APP_VPMAX
#endif

#ifndef ACSBPANE_APP_VPMAX_NEXT
#define ACSBPANE_APP_VPMAX_NEXT GCSBPANE_APP_VPMAX_NEXT
#endif

#ifndef ACSBPANE_APP_DYNINPUT
#define ACSBPANE_APP_DYNINPUT GCSBPANE_APP_DYNINPUT
#endif

#ifndef ACSBPANE_APP_DYNAMICUCS
#define ACSBPANE_APP_DYNAMICUCS GCSBPANE_APP_DYNAMICUCS
#endif

#ifndef ACSBPANE_APP_LAYOUTMODELICONS
#define ACSBPANE_APP_LAYOUTMODELICONS GCSBPANE_APP_LAYOUTMODELICONS
#endif

#ifndef ACSBPANE_APP_MODEL_ICON
#define ACSBPANE_APP_MODEL_ICON GCSBPANE_APP_MODEL_ICON
#endif

#ifndef ACSBPANE_APP_LAYOUT_ICON
#define ACSBPANE_APP_LAYOUT_ICON GCSBPANE_APP_LAYOUT_ICON
#endif

#ifndef ACSBPANE_APP_LAYOUTMORE_ICON
#define ACSBPANE_APP_LAYOUTMORE_ICON GCSBPANE_APP_LAYOUTMORE_ICON
#endif

#ifndef ACSBPANE_APP_ALL
#define ACSBPANE_APP_ALL GCSBPANE_APP_ALL
#endif

#ifndef ACSBPANE_ANNO_STRETCH
#define ACSBPANE_ANNO_STRETCH GCSBPANE_ANNO_STRETCH
#endif

#ifndef ACSBPANE_ANNO_AUTOSCALE
#define ACSBPANE_ANNO_AUTOSCALE GCSBPANE_ANNO_AUTOSCALE
#endif

#ifndef ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL
#define ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL GCSBPANE_ANNO_VIEWPORT_SCALE_LABEL
#endif

#ifndef ACSBPANE_ANNO_VIEWPORT_SCALE
#define ACSBPANE_ANNO_VIEWPORT_SCALE GCSBPANE_ANNO_VIEWPORT_SCALE
#endif

#ifndef ACSBPANE_ANNO_VIEWPORT_LOCK_STATE
#define ACSBPANE_ANNO_VIEWPORT_LOCK_STATE GCSBPANE_ANNO_VIEWPORT_LOCK_STATE
#endif

#ifndef ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL
#define ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL GCSBPANE_ANNO_ANNOTATION_SCALE_LABEL
#endif

#ifndef ACSBPANE_ANNO_ANNOTATION_SCALE
#define ACSBPANE_ANNO_ANNOTATION_SCALE GCSBPANE_ANNO_ANNOTATION_SCALE
#endif

#ifndef ACSBPANE_ANNO_ANNO_ALL_VISIBLE
#define ACSBPANE_ANNO_ANNO_ALL_VISIBLE GCSBPANE_ANNO_ANNO_ALL_VISIBLE
#endif

#ifndef ACSBPANE_ANNO_EMPTY
#define ACSBPANE_ANNO_EMPTY GCSBPANE_ANNO_EMPTY
#endif

#ifndef ACSBPANE_APP_STRETCH
#define ACSBPANE_APP_STRETCH GCSBPANE_APP_STRETCH
#endif

#ifndef ACSBPANE_APP_WORKSPACE
#define ACSBPANE_APP_WORKSPACE GCSBPANE_APP_WORKSPACE
#endif

#ifndef ACSBPANE_APP_WORKSPACE_LOCK
#define ACSBPANE_APP_WORKSPACE_LOCK GCSBPANE_APP_WORKSPACE_LOCK
#endif

#ifndef ACSBPANE_APP_QPROPERTIES
#define ACSBPANE_APP_QPROPERTIES GCSBPANE_APP_QPROPERTIES
#endif

#ifndef ACSBPANE_ANNO_SYNCHSCALES
#define ACSBPANE_ANNO_SYNCHSCALES GCSBPANE_ANNO_SYNCHSCALES
#endif

#ifndef ACSBPANE_APP_QV_LAYOUTS
#define ACSBPANE_APP_QV_LAYOUTS GCSBPANE_APP_QV_LAYOUTS
#endif

#ifndef ACSBPANE_APP_QV_DRAWINGS
#define ACSBPANE_APP_QV_DRAWINGS GCSBPANE_APP_QV_DRAWINGS
#endif

#ifndef ACSBPANE_APP_QV_SPACER
#define ACSBPANE_APP_QV_SPACER GCSBPANE_APP_QV_SPACER
#endif

#ifndef ACSBPANE_APP_QV_PAN
#define ACSBPANE_APP_QV_PAN GCSBPANE_APP_QV_PAN
#endif

#ifndef ACSBPANE_APP_QV_ZOOM
#define ACSBPANE_APP_QV_ZOOM GCSBPANE_APP_QV_ZOOM
#endif

#ifndef ACSBPANE_APP_QV_STEERINGWHEEL
#define ACSBPANE_APP_QV_STEERINGWHEEL GCSBPANE_APP_QV_STEERINGWHEEL
#endif

#ifndef ACSBPANE_APP_QV_SHOWMOTION
#define ACSBPANE_APP_QV_SHOWMOTION GCSBPANE_APP_QV_SHOWMOTION
#endif

#ifndef ACSBPANE_APP_QV_ANNO_SPACER
#define ACSBPANE_APP_QV_ANNO_SPACER GCSBPANE_APP_QV_ANNO_SPACER
#endif

#ifndef ACSBPANE_APP_3DOSNAP
#define ACSBPANE_APP_3DOSNAP GCSBPANE_APP_3DOSNAP
#endif

#ifndef ACSBPANE_APP_WORKSPACE_PERFORMANCE
#define ACSBPANE_APP_WORKSPACE_PERFORMANCE GCSBPANE_APP_WORKSPACE_PERFORMANCE
#endif

#ifndef ACSBPANE_APP_SELECTIONCYCLING
#define ACSBPANE_APP_SELECTIONCYCLING GCSBPANE_APP_SELECTIONCYCLING
#endif

#ifndef ACSBPANE_APP_TRANSPARENCY
#define ACSBPANE_APP_TRANSPARENCY GCSBPANE_APP_TRANSPARENCY
#endif

#ifndef ACSBPANE_APP_INFER
#define ACSBPANE_APP_INFER GCSBPANE_APP_INFER
#endif

#ifndef ACSBPANE_APP_ANNOMONITOR
#define ACSBPANE_APP_ANNOMONITOR GCSBPANE_APP_ANNOMONITOR
#endif

#ifndef ACSBPANE_APP_SELECTION_FILTER
#define ACSBPANE_APP_SELECTION_FILTER GCSBPANE_APP_SELECTION_FILTER
#endif

#ifndef ACSBPANE_APP_GIZMO
#define ACSBPANE_APP_GIZMO GCSBPANE_APP_GIZMO
#endif

#ifndef ACSBPANE_APP_UNITS
#define ACSBPANE_APP_UNITS GCSBPANE_APP_UNITS
#endif

#ifndef ACSBPANE_APP_GEO_SPACER
#define ACSBPANE_APP_GEO_SPACER GCSBPANE_APP_GEO_SPACER
#endif

#ifndef ACSBPANE_APP_GEO_MARKERVISIBILITY
#define ACSBPANE_APP_GEO_MARKERVISIBILITY GCSBPANE_APP_GEO_MARKERVISIBILITY
#endif

#ifndef ACSBPANE_APP_GEO_COORDSYS
#define ACSBPANE_APP_GEO_COORDSYS GCSBPANE_APP_GEO_COORDSYS
#endif

#ifndef ACSBPANE_APP_ISODRAFT
#define ACSBPANE_APP_ISODRAFT GCSBPANE_APP_ISODRAFT
#endif

#ifndef ACSBPANE_APP_HARDWAREACCELERATION
#define ACSBPANE_APP_HARDWAREACCELERATION GCSBPANE_APP_HARDWAREACCELERATION
#endif

#ifndef ACSBPANE_APP_ADD_CLEANSCREEN
#define ACSBPANE_APP_ADD_CLEANSCREEN GCSBPANE_APP_ADD_CLEANSCREEN
#endif

#ifndef ACSBPANE_APP_ADD_CUSTOMIZATION
#define ACSBPANE_APP_ADD_CUSTOMIZATION GCSBPANE_APP_ADD_CUSTOMIZATION
#endif

#ifndef AcApStatusBar
#define AcApStatusBar GcApStatusBar
#endif

#ifndef AcStatusBarMenuItem
#define AcStatusBarMenuItem GcStatusBarMenuItem
#endif


