/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../inc/GcTcUiCatalogViewItem.h"
#include "AcTc.h"
#include "AcTcUI.h"
#ifndef ACTCUI_CVISTYLE_PUSHBUTTON
#define ACTCUI_CVISTYLE_PUSHBUTTON GCTCUI_CVISTYLE_PUSHBUTTON
#endif

#ifndef ACTCUI_CVISTYLE_SHOWTEXT
#define ACTCUI_CVISTYLE_SHOWTEXT GCTCUI_CVISTYLE_SHOWTEXT
#endif

#ifndef ACTCUI_CVISTYLE_RIGHTTEXT
#define ACTCUI_CVISTYLE_RIGHTTEXT GCTCUI_CVISTYLE_RIGHTTEXT
#endif

#ifndef ACTCUI_CVISTYLE_FLYOUT
#define ACTCUI_CVISTYLE_FLYOUT GCTCUI_CVISTYLE_FLYOUT
#endif

#ifndef ACTCUI_CVISTYLE_FULLROW
#define ACTCUI_CVISTYLE_FULLROW GCTCUI_CVISTYLE_FULLROW
#endif

#ifndef ACTCUI_CVISTYLE_HIDEIMAGE
#define ACTCUI_CVISTYLE_HIDEIMAGE GCTCUI_CVISTYLE_HIDEIMAGE
#endif

#ifndef ACTCUI_CVISTYLE_TEXT
#define ACTCUI_CVISTYLE_TEXT GCTCUI_CVISTYLE_TEXT
#endif

#ifndef ACTCUI_CVISTYLE_SEPARATOR
#define ACTCUI_CVISTYLE_SEPARATOR GCTCUI_CVISTYLE_SEPARATOR
#endif

#ifndef ACTCUI_CVISTATE_HIGHLIGHTED
#define ACTCUI_CVISTATE_HIGHLIGHTED GCTCUI_CVISTATE_HIGHLIGHTED
#endif

#ifndef ACTCUI_CVISTATE_SELECTED
#define ACTCUI_CVISTATE_SELECTED GCTCUI_CVISTATE_SELECTED
#endif

#ifndef ACTCUI_CVISTATE_HALO
#define ACTCUI_CVISTATE_HALO GCTCUI_CVISTATE_HALO
#endif

#ifndef ACTCUI_CVISTATE_FOCUSED
#define ACTCUI_CVISTATE_FOCUSED GCTCUI_CVISTATE_FOCUSED
#endif

#ifndef ACTCUI_CVIR_BOUNDS
#define ACTCUI_CVIR_BOUNDS GCTCUI_CVIR_BOUNDS
#endif

#ifndef ACTCUI_CVIR_IMAGE
#define ACTCUI_CVIR_IMAGE GCTCUI_CVIR_IMAGE
#endif

#ifndef ACTCUI_CVIR_LABEL
#define ACTCUI_CVIR_LABEL GCTCUI_CVIR_LABEL
#endif

#ifndef ACTCUI_CVIR_USEFULLLABEL
#define ACTCUI_CVIR_USEFULLLABEL GCTCUI_CVIR_USEFULLLABEL
#endif

#ifndef ACTCUI_CVIR_TRIGGER
#define ACTCUI_CVIR_TRIGGER GCTCUI_CVIR_TRIGGER
#endif

#ifndef ACTCUI_CVIR_WORLDRECT
#define ACTCUI_CVIR_WORLDRECT GCTCUI_CVIR_WORLDRECT
#endif

#ifndef CAcTcUiCatalogViewItem
#define CAcTcUiCatalogViewItem CGcTcUiCatalogViewItem
#endif

#ifndef CAcTcUiCatalogViewItemArray
#define CAcTcUiCatalogViewItemArray CGcTcUiCatalogViewItemArray
#endif

#ifndef CAcTcUiCatalogView
#define CAcTcUiCatalogView CGcTcUiCatalogView
#endif
