/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../inc/gduiGroupCtrl.h"
#include "acarray.h"

#ifndef AdUiBmpBtnFcnPtr
#define AdUiBmpBtnFcnPtr GdUiBmpBtnFcnPtr
#endif

#ifndef AdUiGroupCtrlData
#define AdUiGroupCtrlData GdUiGroupCtrlData
#endif

#ifndef AdUiBmpBtnData
#define AdUiBmpBtnData GdUiBmpBtnData
#endif

#ifndef CAdUiGroupCtrl
#define CAdUiGroupCtrl CGdUiGroupCtrl
#endif


#ifndef ADUIGROUPCTRLDATALIST
#define ADUIGROUPCTRLDATALIST GDUIGROUPCTRLDATALIST
#endif

#ifndef ADUIHEADERBTNLIST
#define ADUIHEADERBTNLIST GDUIHEADERBTNLIST
#endif


#ifndef ADUI_NCHT_BASE
#define ADUI_NCHT_BASE GDUI_NCHT_BASE
#endif

#ifndef ADUI_NCHT_TITLE
#define ADUI_NCHT_TITLE GDUI_NCHT_TITLE
#endif

#ifndef ADUI_NCHT_CHEVRON
#define ADUI_NCHT_CHEVRON GDUI_NCHT_CHEVRON
#endif

#ifndef ADUI_NCHT_BUTTON
#define ADUI_NCHT_BUTTON GDUI_NCHT_BUTTON
#endif


#ifndef ADUI_GROUP_BORDER_SIZE
#define ADUI_GROUP_BORDER_SIZE GDUI_GROUP_BORDER_SIZE
#endif

#ifndef ADUI_GROUP_TITLE_HEIGHT
#define ADUI_GROUP_TITLE_HEIGHT GDUI_GROUP_TITLE_HEIGHT
#endif

#ifndef ADUI_GROUP_TITLE_BEVELSIZE
#define ADUI_GROUP_TITLE_BEVELSIZE GDUI_GROUP_TITLE_BEVELSIZE
#endif

#ifndef ADUI_GROUP_TITLE_TEXTLEFT
#define ADUI_GROUP_TITLE_TEXTLEFT GDUI_GROUP_TITLE_TEXTLEFT
#endif

#ifndef ADUI_GROUP_TITLE_TEXTTOP
#define ADUI_GROUP_TITLE_TEXTTOP GDUI_GROUP_TITLE_TEXTTOP
#endif

#ifndef ADUI_GROUP_TITLE_TEXTBOTTOM
#define ADUI_GROUP_TITLE_TEXTBOTTOM GDUI_GROUP_TITLE_TEXTBOTTOM
#endif

#ifndef ADUI_GROUP_BUTTON_SIZE
#define ADUI_GROUP_BUTTON_SIZE GDUI_GROUP_BUTTON_SIZE
#endif

#ifndef ADUI_GROUP_BUTTONS_RIGHT
#define ADUI_GROUP_BUTTONS_RIGHT GDUI_GROUP_BUTTONS_RIGHT
#endif
  
#ifndef ADUI_GROUP_CHEVRON_TOPPADDING
#define ADUI_GROUP_CHEVRON_TOPPADDING GDUI_GROUP_CHEVRON_TOPPADDING
#endif

#ifndef ADUI_GROUP_CHEVRON_BOTTOMPADDING
#define ADUI_GROUP_CHEVRON_BOTTOMPADDING GDUI_GROUP_CHEVRON_BOTTOMPADDING
#endif

#ifndef ADUI_GROUP_BUTTON_TOPPADDING
#define ADUI_GROUP_BUTTON_TOPPADDING GDUI_GROUP_BUTTON_TOPPADDING
#endif

#ifndef ADUI_GROUP_BUTTON_BOTTOMPADDING
#define ADUI_GROUP_BUTTON_BOTTOMPADDING GDUI_GROUP_BUTTON_BOTTOMPADDING
#endif

#ifndef ADUI_GROUP_BUTTON_SPACE
#define ADUI_GROUP_BUTTON_SPACE GDUI_GROUP_BUTTON_SPACE
#endif

#ifndef ADUI_GROUP_CHEVRON_RIGHT
#define ADUI_GROUP_CHEVRON_RIGHT GDUI_GROUP_CHEVRON_RIGHT
#endif

#ifndef ADUI_GROUP_EXPANDER_RIGHT_OFFSET
#define ADUI_GROUP_EXPANDER_RIGHT_OFFSET GDUI_GROUP_EXPANDER_RIGHT_OFFSET
#endif

#ifndef ADUI_GROUP_CHILD_VERT_SPACE
#define ADUI_GROUP_CHILD_VERT_SPACE GDUI_GROUP_CHILD_VERT_SPACE
#endif


#ifndef ADUI_GROUP_BUTTON_DISABLE_FLAG
#define ADUI_GROUP_BUTTON_DISABLE_FLAG GDUI_GROUP_BUTTON_DISABLE_FLAG
#endif

#ifndef ADUI_GROUP_BUTTON_SELECTED_FLAG
#define ADUI_GROUP_BUTTON_SELECTED_FLAG GDUI_GROUP_BUTTON_SELECTED_FLAG
#endif

#ifndef ADUI_GROUP_BUTTON_ID_MASK
#define ADUI_GROUP_BUTTON_ID_MASK GDUI_GROUP_BUTTON_ID_MASK
#endif

#ifndef ADUI_GROUP_STYLE_CHEVRON
#define ADUI_GROUP_STYLE_CHEVRON GDUI_GROUP_STYLE_CHEVRON
#endif

#ifndef ADUI_GROUP_STYLE_SHOWBTNFORCE
#define ADUI_GROUP_STYLE_SHOWBTNFORCE GDUI_GROUP_STYLE_SHOWBTNFORCE
#endif

#ifndef ADUI_GROUP_STYLE_NONACTIVE
#define ADUI_GROUP_STYLE_NONACTIVE GDUI_GROUP_STYLE_NONACTIVE
#endif

#ifndef ADUI_GROUP_STYLE_NOBORDER
#define ADUI_GROUP_STYLE_NOBORDER GDUI_GROUP_STYLE_NOBORDER
#endif

#ifndef ADUI_GROUP_STYLE_TRANSBTN
#define ADUI_GROUP_STYLE_TRANSBTN GDUI_GROUP_STYLE_TRANSBTN
#endif

#ifndef ADUI_GROUP_STYLE_BTNBORDER
#define ADUI_GROUP_STYLE_BTNBORDER GDUI_GROUP_STYLE_BTNBORDER
#endif

#ifndef ADUI_GROUP_STYLE_ACTIVEHEADER
#define ADUI_GROUP_STYLE_ACTIVEHEADER GDUI_GROUP_STYLE_ACTIVEHEADER
#endif

#ifndef ADUI_GROUP_STYLE_OPAQUEIMAGE
#define ADUI_GROUP_STYLE_OPAQUEIMAGE GDUI_GROUP_STYLE_OPAQUEIMAGE
#endif

#ifndef ADUI_GROUP_STYLE_STRETCHIMAGE
#define ADUI_GROUP_STYLE_STRETCHIMAGE GDUI_GROUP_STYLE_STRETCHIMAGE
#endif

#ifndef WM_ADUI_VISIBILITY_CHANGING
#define WM_ADUI_VISIBILITY_CHANGING WM_GDUI_VISIBILITY_CHANGING
#endif
