/////////////////////////////////////////////////////////////////////////////////////////
//
// Please refer to "COPYRIGHT.md" for the relevant copyright statement of this software.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
#pragma once
#include "../../inc/dcdispid.h"

#ifndef ACDC_MAKE_DISPID
#define ACDC_MAKE_DISPID GCDC_MAKE_DISPID
#endif


#ifndef DISPID_IAcDcContentBrowser_AddPaletteItem
#define DISPID_IAcDcContentBrowser_AddPaletteItem DISPID_IGcDcContentBrowser_AddPaletteItem
#endif

#ifndef DISPID_IAcDcContentBrowser_AddNavigatorNode
#define DISPID_IAcDcContentBrowser_AddNavigatorNode DISPID_IGcDcContentBrowser_AddNavigatorNode
#endif

#ifndef DISPID_IAcDcContentBrowser_GetDCFrameWindow
#define DISPID_IAcDcContentBrowser_GetDCFrameWindow DISPID_IGcDcContentBrowser_GetDCFrameWindow
#endif

#ifndef DISPID_IAcDcContentBrowser_SetItemDescription
#define DISPID_IAcDcContentBrowser_SetItemDescription DISPID_IGcDcContentBrowser_SetItemDescription
#endif

#ifndef DISPID_IAcDcContentBrowser_SetPaletteImageList
#define DISPID_IAcDcContentBrowser_SetPaletteImageList DISPID_IGcDcContentBrowser_SetPaletteImageList
#endif

#ifndef DISPID_IAcDcContentBrowser_SetNavigatorImageList
#define DISPID_IAcDcContentBrowser_SetNavigatorImageList DISPID_IGcDcContentBrowser_SetNavigatorImageList
#endif

#ifndef DISPID_IAcDcContentBrowser_SetPaletteMultiSelect
#define DISPID_IAcDcContentBrowser_SetPaletteMultiSelect DISPID_IGcDcContentBrowser_SetPaletteMultiSelect
#endif

#ifndef DISPID_IAcDcContentBrowser_InsertPaletteColumn
#define DISPID_IAcDcContentBrowser_InsertPaletteColumn DISPID_IGcDcContentBrowser_InsertPaletteColumn
#endif

#ifndef DISPID_IAcDcContentBrowser_DeleteAllPaletteItems
#define DISPID_IAcDcContentBrowser_DeleteAllPaletteItems DISPID_IGcDcContentBrowser_DeleteAllPaletteItems
#endif

#ifndef DISPID_IAcDcContentBrowser_GetSelectedNavNodeText
#define DISPID_IAcDcContentBrowser_GetSelectedNavNodeText DISPID_IGcDcContentBrowser_GetSelectedNavNodeText
#endif

#ifndef DISPID_IAcDcContentBrowser_GetCurrentViewMode
#define DISPID_IAcDcContentBrowser_GetCurrentViewMode DISPID_IGcDcContentBrowser_GetCurrentViewMode
#endif

#ifndef DISPID_IAcDcContentBrowser_SetPaletteSubItem
#define DISPID_IAcDcContentBrowser_SetPaletteSubItem DISPID_IGcDcContentBrowser_SetPaletteSubItem
#endif

#ifndef DISPID_IAcDcContentBrowser_SortPaletteItems
#define DISPID_IAcDcContentBrowser_SortPaletteItems DISPID_IGcDcContentBrowser_SortPaletteItems
#endif

#ifndef DISPID_IAcDcContentBrowser_RestorePaletteSelection
#define DISPID_IAcDcContentBrowser_RestorePaletteSelection DISPID_IGcDcContentBrowser_RestorePaletteSelection
#endif

#ifndef DISPID_IAcDcContentBrowser_GetDCStatusBar
#define DISPID_IAcDcContentBrowser_GetDCStatusBar DISPID_IGcDcContentBrowser_GetDCStatusBar
#endif

#ifndef DISPID_IAcDcContentBrowser_GetPaneInfo
#define DISPID_IAcDcContentBrowser_GetPaneInfo DISPID_IGcDcContentBrowser_GetPaneInfo
#endif

#ifndef DISPID_IAcDcContentBrowser_SetPaletteViewType
#define DISPID_IAcDcContentBrowser_SetPaletteViewType DISPID_IGcDcContentBrowser_SetPaletteViewType
#endif

#ifndef DISPID_IAcDcContentBrowser_NavigateTo
#define DISPID_IAcDcContentBrowser_NavigateTo DISPID_IGcDcContentBrowser_NavigateTo
#endif


#ifndef DISPID_IAcDcContentView_Initialize
#define DISPID_IAcDcContentView_Initialize DISPID_IGcDcContentView_Initialize
#endif

#ifndef DISPID_IAcDcContentView_SetImageLists
#define DISPID_IAcDcContentView_SetImageLists DISPID_IGcDcContentView_SetImageLists
#endif

#ifndef DISPID_IAcDcContentView_Refresh
#define DISPID_IAcDcContentView_Refresh DISPID_IGcDcContentView_Refresh
#endif

#ifndef DISPID_IAcDcContentView_NavigatorNodeExpanding
#define DISPID_IAcDcContentView_NavigatorNodeExpanding DISPID_IGcDcContentView_NavigatorNodeExpanding
#endif

#ifndef DISPID_IAcDcContentView_NavigatorNodeCollapsing
#define DISPID_IAcDcContentView_NavigatorNodeCollapsing DISPID_IGcDcContentView_NavigatorNodeCollapsing
#endif

#ifndef DISPID_IAcDcContentView_NavigatorNodeClick
#define DISPID_IAcDcContentView_NavigatorNodeClick DISPID_IGcDcContentView_NavigatorNodeClick
#endif

#ifndef DISPID_IAcDcContentView_NavigatorMouseUp
#define DISPID_IAcDcContentView_NavigatorMouseUp DISPID_IGcDcContentView_NavigatorMouseUp
#endif

#ifndef DISPID_IAcDcContentView_PaletteItemClick
#define DISPID_IAcDcContentView_PaletteItemClick DISPID_IGcDcContentView_PaletteItemClick
#endif

#ifndef DISPID_IAcDcContentView_PaletteItemDblClick
#define DISPID_IAcDcContentView_PaletteItemDblClick DISPID_IGcDcContentView_PaletteItemDblClick
#endif

#ifndef DISPID_IAcDcContentView_PaletteColumnClick
#define DISPID_IAcDcContentView_PaletteColumnClick DISPID_IGcDcContentView_PaletteColumnClick
#endif

#ifndef DISPID_IAcDcContentView_PaletteMouseUp
#define DISPID_IAcDcContentView_PaletteMouseUp DISPID_IGcDcContentView_PaletteMouseUp
#endif

#ifndef DISPID_IAcDcContentView_PaletteMouseDown
#define DISPID_IAcDcContentView_PaletteMouseDown DISPID_IGcDcContentView_PaletteMouseDown
#endif

#ifndef DISPID_IAcDcContentView_RenderPreviewWindow
#define DISPID_IAcDcContentView_RenderPreviewWindow DISPID_IGcDcContentView_RenderPreviewWindow
#endif

#ifndef DISPID_IAcDcContentView_PreviewMouseUp
#define DISPID_IAcDcContentView_PreviewMouseUp DISPID_IGcDcContentView_PreviewMouseUp
#endif

#ifndef DISPID_IAcDcContentView_PaletteBeginDrag
#define DISPID_IAcDcContentView_PaletteBeginDrag DISPID_IGcDcContentView_PaletteBeginDrag
#endif

#ifndef DISPID_IAcDcContentView_ReleaseBrowser
#define DISPID_IAcDcContentView_ReleaseBrowser DISPID_IGcDcContentView_ReleaseBrowser
#endif

#ifndef DISPID_IAcDcContentView_QueryContextMenu
#define DISPID_IAcDcContentView_QueryContextMenu DISPID_IGcDcContentView_QueryContextMenu
#endif

#ifndef DISPID_IAcDcContentView_InvokeCommand
#define DISPID_IAcDcContentView_InvokeCommand DISPID_IGcDcContentView_InvokeCommand
#endif

#ifndef DISPID_IAcDcContentView_IsExpandable
#define DISPID_IAcDcContentView_IsExpandable DISPID_IGcDcContentView_IsExpandable
#endif

#ifndef DISPID_IAcDcContentView_GetLargeIcon
#define DISPID_IAcDcContentView_GetLargeIcon DISPID_IGcDcContentView_GetLargeIcon
#endif

#ifndef DISPID_IAcDcContentView_GetSmallImageListForContent
#define DISPID_IAcDcContentView_GetSmallImageListForContent DISPID_IGcDcContentView_GetSmallImageListForContent
#endif

#ifndef DISPID_IAcDcContentView_GetLargeImageListForContent
#define DISPID_IAcDcContentView_GetLargeImageListForContent DISPID_IGcDcContentView_GetLargeImageListForContent
#endif

#ifndef DISPID_IAcDcContentView_GetCommandString
#define DISPID_IAcDcContentView_GetCommandString DISPID_IGcDcContentView_GetCommandString
#endif

#ifndef DISPID_IAcDcContentView_DeleteItemData
#define DISPID_IAcDcContentView_DeleteItemData DISPID_IGcDcContentView_DeleteItemData
#endif
